set(STM32_LIB_EXTRA_SOURCES ${STM32_LIB_EXTRA_SOURCES}
    ${STM32LIB_SOURCE_FILES}
)

set(STM32_LIB_EXTRA_HEADERS ${STM32_LIB_EXTRA_HEADERS}
    ${STM32LIB_HEADERS_DIRS}
)

set(STM32_LIB_EXTRA_LIBS ${STM32_LIB_EXTRA_LIBS}
    ${STM32LIB_EXTRA_LIBS}
)


set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH}
    ${CMAKE_CURRENT_LIST_DIR}
    ${CMAKE_CURRENT_LIST_DIR}/STM32F0xx_HAL_Driver/
)
