set(STM32LIB_HEADERS_DIRS ${STM32LIB_HEADERS_DIRS}
    ${CMAKE_CURRENT_LIST_DIR}/../../Inc/stm32f0xx
)

set(STM32LIB_SOURCE_FILES ${STM32LIB_SOURCE_FILES}
    ${CMAKE_CURRENT_LIST_DIR}/../../Src/stm32f0xx/stm32f0xx_hal.c
)